### ISSUE TITLE
shouldComponentUpdate shouldnt be noop

### ISSUE THREAD

**Issue by Kamahl19** [MiroslavPetrik/react-hook-component#2]
`shouldComponentUpdate ` should return `true` by default

**Comment by MiroslavPetrik** [comment]
true

**Comment by MiroslavPetrik** [comment]
I think that I will fix this, when the enzyme will support the `memo` higher order function.
Currently the method is not being called anyway (it's commented).

Is that ok? @Kamahl19 
Hope you are not using in production YET.
