### ISSUE TITLE
Use React's component tests

### ISSUE THREAD

**Issue by Kamahl19** [MiroslavPetrik/react-hook-component#3]
It should pass all react's component and lifecycle tests such as
https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/__tests__/ReactComponent-test.js
and
https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/__tests__/ReactComponentLifeCycle-test.js

**Comment by MiroslavPetrik** [comment]
Lot's of work ahead, I see...
